[UI/#4] like/ 저장 UI 작업 완료
Keyneez/Keyneez-AOS-Lab pull request #10
Opened 2022-12-29 07:53 UTC by 0zlrlo

## 관련 이슈
- closed #4 

## 작업 내역
- like 화면 xml 구현 완료

## PR 포인트
- 리사이클러뷰 부분이 잘 됐는지 확인 받고 싶습니다!

## 실행화면

2022-12-29 12:50 UTC, b1urrrr requested changes
뷰 짜느라 고생하셨습니다🥰
string도 추가하면서 사용하고, dp값도 지정 안하면서 잘 구현하셨네요 👍
이건 크게 중요하진 않지만 lint 수정한 커밋은 UI 보다는 FIX 나 MOD, DEL 태그가 더 적합할 것 같아요!

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
>      }
```suggestion
class LikeFragment : BindingFragment<FragmentLikeBinding>(R.layout.fragment_like) {
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // 여기서 코드 작성
    }
```

LikeFragment가 상속받는 BindingFragment를 보시면 binding 변수를 생성하고 `onDestroyView`에서 binding 변수를 null로 초기화하는 코드가 이미 포함되어 있어요! 중복되는 코드들은 지워주세요 :)

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
>      }
```suggestion
class LikeFragment : BindingFragment<FragmentLikeBinding>(R.layout.fragment_like) {
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // 여기서 코드 작성
    }
    
    companion object {
        fun newInstance(): LikeFragment {
            return LikeFragment()
        }
    }
}
```
세미나에서 프래그먼트에 newInstance() 함수를 만들어두는 게 좋다고 언급했었어요!

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
> +        tools:context=".presentation.main.home.HomeFragment">
`tools:context` 속성도 layout 안에 넣어주세요!

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
> +            android:id="@+id/rv_like_grid"
네이밍이 grid 보다는 어떤 아이템을 담는 리사이클러뷰인지 명시해주는 게 좋을 것 같아요!
EX) rv_like, rv_like_store, rv_like_save ...? 뭐가 좋을까요

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/values/strings.xml
> +    <string name="like_content">청소년 영화관 할인</string>
string 추가 굿굿 👍👍

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +<!--    서버 통신할 때 개발자만 보이게끔 하고 싶으면 tools 사용하기-->
code reformat 단축키 한번씩만 눌러주세요!

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
> +            android:layout_marginTop="43dp"
`marginTop`으로 하면 스크롤하는 구간이 작아져서 `paddingTop`으로 수정해주세요!

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
> +            app:layout_constraintEnd_toEndOf="@id/layout_like" />
ImageButton의 경우에는 touch target 용도로 padding으로 최대 12dp를 지정해주세요!

2022-12-29 12:50 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
> +            android:layout_marginEnd="24dp"
```suggestion
            android:layout_marginHorizontal="24dp"
```
지금도 괜찮지만 이렇게도 쓸 수 있어요!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
> +        tools:context=".presentation.main.home.HomeFragment">
완료!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
>      }
넵 완료!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
>      }
넵 참고하도록 하겠습니당!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
> +            app:layout_constraintEnd_toEndOf="@id/layout_like" />
완료!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
> +            android:id="@+id/rv_like_grid"
넵!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
> +            android:layout_marginEnd="24dp"
넵! 수정하였습니당

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
> +            android:layout_marginTop="43dp"
넵!

2022-12-29 16:45 UTC, 0zlrlo commented on app/src/main/res/layout/item_like_content.xml
> +<!--    서버 통신할 때 개발자만 보이게끔 하고 싶으면 tools 사용하기-->
넵!

2022-12-30 06:45 UTC, b1urrrr requested changes
코리 반영하느라 고생하셨습니다!
몇 가지만 더 수정 부탁드려요 ☺️

2022-12-30 06:45 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +            tools:srcCompat="@drawable/img_like_background" />
```suggestion
        <ImageView
            android:id="@+id/iv_like_background"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:scaleType="centerCrop"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            tools:srcCompat="@drawable/img_like_background" />
```
아이템 높이가 이미지의 높이에 따라 달라질 것 같은데 이걸 항상 일정한 높이가 되도록 만들어봅시다!
1. 이미지뷰 높이가 항상 일정하도록 height를 `0dp`로 하고 `layout_constraintBottom_toBottomOf="parent"`를 추가해주세요 (계속)

2022-12-30 06:45 UTC, b1urrrr commented on app/src/main/res/layout/item_like_content.xml
> +            tools:text="@string/like_content" />
```suggestion
        <TextView
            android:id="@+id/tv_like_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="70dp"
            android:layout_marginBottom="112dp"
            android:textStyle="bold"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/tv_like_date"
            app:layout_constraintBottom_toBottomOf="@id/layout_like_rv"
            tools:text="@string/like_content" />
```
2. textView 기준으로 이미지 하단에 112dp가 주어지도록 제약 조건을 추가해주세요!

2022-12-30 06:45 UTC, b1urrrr commented on app/build.gradle
> +    implementation("androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha05")
이건 빼도 될 것 같아요!

2022-12-30 06:45 UTC, b1urrrr commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
둘 다 안스에서 추천하는 최신 버전으로 업그레이드해주세요!

2022-12-30 07:02 UTC, b1urrrr commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
저희 찐 개발 리포에서 쓸 Coil 쓰는 법을 찾아봐도 좋을 것 같습니당

2022-12-30 07:05 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
> +            android:paddingVertical="12dp"
이런건 그냥 padding으로 줘도 되겠네요!

2022-12-30 13:52 UTC, DongjooSEO approved these changes
첫 PR 수고해써!! 
나도 얼른 완성해서 올려야겠다.

2022-12-30 13:52 UTC, DongjooSEO commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeAdapter.kt
> +    inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
이거 inner class 는 안쓰는 게 좋다고 들었어!

2022-12-30 13:52 UTC, DongjooSEO commented on app/src/main/res/layout/item_like_content.xml
> +        <!--먼저 오는 것이 화면 맨 뒤로 오게 된다-->
확인!!

2022-12-30 13:54 UTC, 0zlrlo commented on app/src/main/res/layout/item_like_content.xml
> +            tools:srcCompat="@drawable/img_like_background" />
넵!

2022-12-30 13:54 UTC, 0zlrlo commented on app/src/main/res/layout/item_like_content.xml
> +            tools:text="@string/like_content" />
넵!

2022-12-30 13:56 UTC, 0zlrlo commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
넵 버전 수정 완료했습니당

2022-12-30 13:57 UTC, 0zlrlo commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeAdapter.kt
> +    inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
오홍 이거에 대해서 더 알아볼게용

2022-12-30 14:11 UTC, b1urrrr approved these changes
크으 고생하셨습니다 👍

2022-12-30 14:12 UTC, merged