[FEAT/#11] like / 저장 탭 구현
Keyneez/Keyneez-AOS-Lab pull request #14
Opened 2023-01-01 07:42 UTC by 0zlrlo

## 관련 이슈
- closed #11 

## 작업 내역
- 저장 뷰 기능 구현

## PR 포인트
- 스크롤이 되긴 되는데 끝까지 안되는 거 같습니다. 이 부분을 확인 해주시면 감사하겠습니다.

## 실행화면

2023-01-01 08:37 UTC, b1urrrr requested changes
리사이클러뷰까지 너무 잘 구현했어요!!!
ViewModel에 데이터 관련된 로직을 분리시켜보는 걸 추천드립니다 :)

2023-01-01 08:37 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
>              tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
```
<androidx.recyclerview.widget.RecyclerView
          android:id="@+id/rv_like_content"
          android:layout_width="match_parent"
          android:layout_height="0dp"
          android:paddingHorizontal="20dp"
          android:layout_marginTop="9dp"
          android:paddingTop="26dp"
          app:layout_constraintTop_toBottomOf="@id/iv_like_baseline"
          app:layout_constraintBottom_toBottomOf="parent"
          tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
          tools:listitem="@layout/item_like_content"
          tools:spanCount="2" />
```
리사이클러뷰가 화면 안에서만 보이도록 제약 조건을 추가해주세요!
그리고 `marginHorizontal`을 `paddingHorizontal`로 수정하는 게 보기 예쁠 것 같네요~

2023-01-01 08:37 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeAdapter.kt
>      }
ViewHolder를 구현할 때 binding 변수를 활용하면 findViewById 대신 뷰바인딩으로 bind 함수를 구현할 수 있어요!
[제가 과제 때 사용한 코드](https://github.com/IN-SOPT-ANDROID/chaeyeon-jeon/blob/de09310879fdf4e1a94bf669c12cc69aa160165b/app/src/main/java/org/sopt/sample/presentation/main/home/FollowerAdapter.kt#L59)를 참고해주세요!

2023-01-01 08:37 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
> +            likeAdapter.notifyDataSetChanged()
Adapter 안에 data를 갱신해주는 함수를 구현해서 호출하는 형식으로 수정해봐도 좋을 것 같아요! 이것도 제 코드를 참고해보면 좋을 것 같아요~

2023-01-01 10:16 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
>              tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
paddingHorizontal로 고치니 에러가 생기더라구요! 리사이클러뷰가 화면을 넘어가는 것 같습니다. 조금 더 생각해 보겠습니다
그리고 화면 안에서만 보이도록 하는 제약 조건이 혹시 무엇인지 알 수 있을까요? 다른 분들의 코드를 봐도 잘 모르겠습니다..ㅠㅠ

2023-01-01 10:16 UTC, 0zlrlo commented on app/src/main/java/com/lab/keyneez/presentation/main/like/LikeFragment.kt
> +            likeAdapter.notifyDataSetChanged()
넵 참고해서 고치겠습니다!

2023-01-01 14:16 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
>              tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
제가 올려드린 코드대로 하면 저는 잘 돌아갔어요!

2023-01-01 14:25 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_like.xml
>              tools:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
엇 그럼 그걸 바탕으로 다시 코드를 짜 볼게요!

2023-01-01 15:25 UTC, DongjooSEO approved these changes

2023-01-01 18:02 UTC, b1urrrr commented on app/src/main/res/layout/fragment_like.xml
>              app:layout_constraintTop_toBottomOf="@id/iv_like_baseline"
android:clipToPadding="false"

이 속성 하나만 추가해주세요! 이 속성을 추가해야 padding으로 지정한 부분들이 스크롤이 돼요

2023-01-01 18:04 UTC, b1urrrr commented
![dd](https://user-images.githubusercontent.com/70993562/210180561-c55f58b6-5600-4002-8523-124c169bec70.png)

코드 리뷰를 전부 반영한 다음에 저에게 리뷰를 re-request 해주시면 저한테 알람이 전송돼서 확인하기 편해요 :)

2023-01-02 07:21 UTC, b1urrrr approved these changes
고생하셨습니다!!

2023-01-02 07:21 UTC, merged