[UI/#3] 홈(infomain) 뷰페이저 뷰 구현
Keyneez/Keyneez-AOS-Lab pull request #15
Opened 2023-01-01 08:23 UTC by DongjooSEO

## 관련 이슈
- closed #3 

## 작업 내역
- 홈 viewPager구현
- 홈 xml 작성

## PR 포인트
일단 뷰페이저 연결했구 이제 adapter로 리사이클러뷰 붙일 예정입니다!~

## 실행화면

2023-01-01 09:02 UTC, b1urrrr reviewed
와 너무 고생많았어😭
뷰페이저까지 잘 구현했네 이따가 다시 코드 자세히 보면서 리뷰 할게요!!

2023-01-01 09:12 UTC, 0zlrlo approved these changes
고생하셨습니당!!

2023-01-01 09:12 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_home.xml
> +            app:layout_constraintTop_toTopOf="parent" />
버튼 같은 경우는 padding을 줌으로써 누를 수 있는 공간을 더 확보하면 좋다고 합니다! 12dp정도 주면 될 것 같습니다!

2023-01-01 09:12 UTC, 0zlrlo commented on app/src/main/res/layout/fragment_home.xml
> +                android:text="추천" />
text로 하드코딩한 부분을 string으로 바꿔주세요!

2023-01-01 09:12 UTC, 0zlrlo commented on app/src/main/java/com/lab/keyneez/presentation/main/home/HomeFragment.kt
> +        val viewPager = binding.vpHome
와 뷰페이저 구현한 언니 넘나 멋져...

2023-01-01 17:54 UTC, b1urrrr requested changes
뷰페이저 구현하시느라 고생하셨습니다🥲
여기에 리사이클러뷰만 구현하면 HomeFragment는 완성되겠네요!!
화이팅이에요 🔥

2023-01-01 17:54 UTC, b1urrrr commented on app/build.gradle
> +            minifyEnabled true
혹시 true로 바꾼 이유가 있을까요?

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/home/HomeFragment.kt
> +        val homeTabTitles = listOf<String>("추천", "인기", "최신")
이런 텍스트들도 다 strings.xml에 추가해주세요!
Alt + Enter > Extract string resource 를 통해 빠르게 추가할 수 있습니다.
(나중에 strings.xml에서 코드들 위치만 적당히 옮겨주세요!)

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/home/HomeFragment.kt
> +    private lateinit var ViewPagerAdapter: HomeVPFragmentAdapter
이 변수는 선언만 하고 사용하지 않고 있네요!

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/home/HomeFragment.kt
> +        }.attach()
onCreate()에 로직이 몰려있는데, [저희 컨벤션](https://www.notion.so/function-7f35b10c5e2d42418466d31b04b80401)에 맞게 함수화를 하는 게 좋을 것 같아요!

EX) initHomeViewPagerAdapter

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/res/drawable/logoa.xml
> +    android:viewportWidth="80"
[drawable file 컨벤션](https://www.notion.so/drawable-file-name-c041787576234524909069e1b5f9baf4)에 맞게 네이밍해주세요!

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/res/layout/fragment_home.xml
> +            android:id="@+id/tv_home_logo"
```suggestion
            android:id="@+id/iv_home_logo"
```

실수 발견!

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/res/layout/fragment_home.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
저는 최상단 레이아웃에도 id값을 지정해주는 걸 권장해요!
나중에 키보드 내리기 구현할 때 유용하답니다.

EX) layout_home

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/res/layout/fragment_home.xml
> +                android:text="@string/home_new" />
얘네도 id 값 넣어주면 좋을 것 같아요!

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/res/layout/item_infomain.xml
> +        app:layout_constraintBottom_toBottomOf="parent"/>
strings에 추가되지 않는 텍스트들 모두 추가해주세요!
(Alt + Enter 활용하면 짱 빠르게 추가할 수 있어요)

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/home/HomeFragment.kt
> +        val homeTabTitles = listOf<String>("추천", "인기", "최신")
보니까 strings에는 이미 추가되어 있네요! `getString()` 함수를 활용해서 불러올 수 있답니다!

EX) `getString(R.string.home_recommand)`

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/java/com/lab/keyneez/presentation/main/home/adapter/HomeVPFragmentAdapter.kt
> +            2 -> return HomeVPNewFragment()
프래그먼트 앞에 HomeVP를 붙이는 게 좋은 네이밍인지 잘 모르겠네요...
RecommendInfoFragment, PopularInfoFragment, NewInfoFragment
이런식의 네이밍은 어떤가요?

2023-01-01 17:54 UTC, b1urrrr commented on app/src/main/res/drawable/ic_search.xml
> +</vector>
[컨벤션](https://www.notion.so/drawable-file-name-c041787576234524909069e1b5f9baf4)에 맞에 where를 추가해주세요!

EX) ic_home_search

2023-01-02 04:07 UTC, DongjooSEO commented on app/build.gradle
> +            minifyEnabled true
ㅋㅋㅋㅋㅋㅋ이거 전에 그 오류 이것저것 해본다고 했을 때,, 
다시 원래대로 돌려둘게요

2023-01-02 07:31 UTC, b1urrrr approved these changes
LGTM~

2023-01-02 07:32 UTC, b1urrrr commented
지은이가 머지한 내용 풀 받고 푸시해서 머지해주세요!

2023-01-02 07:42 UTC, merged